
import { GoogleGenAI } from "@google/genai";
import { UpscaleConfig } from '../types';

// Getter for lazy initialization to avoid process.env access at module load time
const getAiClient = () => {
  if (!process.env.API_KEY) {
    console.error("API_KEY is missing from process.env");
  }
  return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const result = reader.result as string;
      // Remove the data URL prefix (e.g., "data:image/jpeg;base64,")
      const base64 = result.split(',')[1];
      resolve(base64);
    };
    reader.onerror = (error) => reject(error);
  });
};

export const generatePrompt = (config: UpscaleConfig): string => {
  // Use custom prompt if in custom mode and a prompt is provided
  if (config.mode === 'custom' && config.customPrompt && config.customPrompt.trim().length > 0) {
    return config.customPrompt;
  }

  // Fallback to 'both' logic if in custom mode but empty prompt, or normal mode logic
  const effectiveMode = config.mode === 'custom' ? 'both' : config.mode;

  // Refined Prompt to avoid IMAGE_RECITATION
  // We frame this as a "Generation" and "Reconstruction" task rather than just "Restoration"
  let prompt = "Task: Generate a high-definition version of the provided image with significantly improved quality. ";

  // Mode Selection Logic
  switch (effectiveMode) {
    case 'upscale':
      prompt += `Action: Reconstruct the image at ${config.scale}x resolution (target 2K/4K). Aggressively sharpen edges and hallucinate plausible fine details to remove blur. `;
      break;
    case 'enhance':
      prompt += "Action: Refine the image clarity. Remove all JPEG compression artifacts, grain, and sensor noise. Balance the lighting and color saturation for a professional look. ";
      break;
    case 'both':
    default:
      prompt += `Action: Reconstruct the image at ${config.scale}x resolution. Simultaneously remove noise/artifacts and sharpen fine details. The output must be crisp and photorealistic. `;
      break;
  }

  // Feature Constraints
  if (config.preserveText) {
    prompt += "Constraint: Text and logos MUST remain legible, straight, and spelled correctly. Sharpen the text boundaries. ";
  } else {
      prompt += "Constraint: Prioritize visual aesthetics. ";
  }

  if (config.enhanceFace) {
    prompt += "Constraint: Enhance facial features naturally (eyes, skin texture) without altering the person's identity. ";
  }

  if (config.denoise) {
    prompt += "Constraint: Apply strong denoising to smooth out flat areas. ";
  }

  prompt += "Output: Return ONLY the generated image.";
  
  return prompt;
};

export const processImage = async (
  file: File, 
  config: UpscaleConfig,
  onProgress: (progress: number) => void
): Promise<string> => {
  try {
    onProgress(10);
    const base64Data = await fileToBase64(file);
    onProgress(30);

    const prompt = generatePrompt(config);

    onProgress(50);

    const ai = getAiClient();
    
    // Call Gemini Nano Banana (gemini-2.5-flash-image)
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: [
        {
          parts: [
            { 
              inlineData: { 
                mimeType: file.type || 'image/jpeg', 
                data: base64Data 
              } 
            },
            { text: prompt }
          ]
        }
      ],
      config: {
        // A lower temperature can sometimes help with fidelity, but for upscaling we might want a bit of creativity to avoid recitation
        temperature: 0.4 
      }
    });

    onProgress(90);

    // Extract the image from the response
    const parts = response.candidates?.[0]?.content?.parts;
    
    // Check for refusal/safety blocks
    const finishReason = response.candidates?.[0]?.finishReason;
    if (finishReason && finishReason !== 'STOP') {
       let errorMsg = `Model stopped generation. Reason: ${finishReason}`;
       
       if (finishReason === 'RECITATION') {
         errorMsg = "The model detected that the output would be too similar to the input (Recitation). Try using the 'Enhance' mode or changing the upscale factor.";
       } else if (finishReason === 'SAFETY') {
         errorMsg = "The image triggered the model's safety filters.";
       }

       throw new Error(errorMsg);
    }

    if (!parts || parts.length === 0) {
      console.error("Empty parts in response:", response);
      throw new Error("No content generated by the model.");
    }

    for (const part of parts) {
      if (part.inlineData && part.inlineData.data) {
        const base64Image = part.inlineData.data;
        // Determine MIME type (default to png if not specified, usually 2.5 flash returns png or jpeg)
        const mimeType = part.inlineData.mimeType || 'image/png';
        onProgress(100);
        return `data:${mimeType};base64,${base64Image}`;
      }
    }

    // If no image found in parts, check if there's text describing an error
    const textPart = parts.find(p => p.text);
    if (textPart) {
      console.warn("Model returned text instead of image:", textPart.text);
      throw new Error("The model returned text instead of an image. It may have refused the specific request.");
    }

    throw new Error("No image data found in the response.");

  } catch (error) {
    console.error("AI Processing Error:", error);
    throw error;
  }
};

export const formatBytes = (bytes: number, decimals = 2) => {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
};