/**
 * Credit costs configuration
 * Centralized constants for all credit-related magic numbers
 */

export const CREDIT_COSTS = {
  // Base credit costs by mode
  BASE_UPSCALE_COST: 1,
  BASE_ENHANCE_COST: 2,
  BASE_BOTH_COST: 2,
  BASE_CUSTOM_COST: 2,

  // Model credit multipliers
  REAL_ESRGAN_MULTIPLIER: 1,
  GFPGAN_MULTIPLIER: 2,
  NANO_BANANA_MULTIPLIER: 2,
  CLARITY_UPSCALER_MULTIPLIER: 4,
  NANO_BANANA_PRO_MULTIPLIER: 8,

  // Free tier default credits
  DEFAULT_FREE_CREDITS: 10,
  DEFAULT_TRIAL_CREDITS: 0,

  // Credit pack amounts
  SMALL_PACK_CREDITS: 50,
  MEDIUM_PACK_CREDITS: 200,
  LARGE_PACK_CREDITS: 600,

  // Subscription credit amounts
  HOBBY_MONTHLY_CREDITS: 200,
  PRO_MONTHLY_CREDITS: 1000,
  BUSINESS_MONTHLY_CREDITS: 5000,

  // Warning thresholds
  LOW_CREDIT_WARNING_THRESHOLD: 5,
  CREDIT_WARNING_PERCENTAGE: 0.2,
} as const;

// Computed credit costs for each model and mode
export const MODEL_CREDIT_COSTS = {
  'real-esrgan': {
    upscale: CREDIT_COSTS.BASE_UPSCALE_COST * CREDIT_COSTS.REAL_ESRGAN_MULTIPLIER,
    enhance: CREDIT_COSTS.BASE_ENHANCE_COST * CREDIT_COSTS.REAL_ESRGAN_MULTIPLIER,
    both: CREDIT_COSTS.BASE_BOTH_COST * CREDIT_COSTS.REAL_ESRGAN_MULTIPLIER,
    custom: CREDIT_COSTS.BASE_CUSTOM_COST * CREDIT_COSTS.REAL_ESRGAN_MULTIPLIER,
  },
  gfpgan: {
    upscale: CREDIT_COSTS.BASE_UPSCALE_COST * CREDIT_COSTS.GFPGAN_MULTIPLIER,
    enhance: CREDIT_COSTS.BASE_ENHANCE_COST * CREDIT_COSTS.GFPGAN_MULTIPLIER,
    both: CREDIT_COSTS.BASE_BOTH_COST * CREDIT_COSTS.GFPGAN_MULTIPLIER,
    custom: CREDIT_COSTS.BASE_CUSTOM_COST * CREDIT_COSTS.GFPGAN_MULTIPLIER,
  },
  'nano-banana': {
    upscale: CREDIT_COSTS.BASE_UPSCALE_COST * CREDIT_COSTS.NANO_BANANA_MULTIPLIER,
    enhance: CREDIT_COSTS.BASE_ENHANCE_COST * CREDIT_COSTS.NANO_BANANA_MULTIPLIER,
    both: CREDIT_COSTS.BASE_BOTH_COST * CREDIT_COSTS.NANO_BANANA_MULTIPLIER,
    custom: CREDIT_COSTS.BASE_CUSTOM_COST * CREDIT_COSTS.NANO_BANANA_MULTIPLIER,
  },
  'clarity-upscaler': {
    upscale: CREDIT_COSTS.BASE_UPSCALE_COST * CREDIT_COSTS.CLARITY_UPSCALER_MULTIPLIER,
    enhance: CREDIT_COSTS.BASE_ENHANCE_COST * CREDIT_COSTS.CLARITY_UPSCALER_MULTIPLIER,
    both: CREDIT_COSTS.BASE_BOTH_COST * CREDIT_COSTS.CLARITY_UPSCALER_MULTIPLIER,
    custom: CREDIT_COSTS.BASE_CUSTOM_COST * CREDIT_COSTS.CLARITY_UPSCALER_MULTIPLIER,
  },
  'nano-banana-pro': {
    upscale: CREDIT_COSTS.BASE_UPSCALE_COST * CREDIT_COSTS.NANO_BANANA_PRO_MULTIPLIER,
    enhance: CREDIT_COSTS.BASE_ENHANCE_COST * CREDIT_COSTS.NANO_BANANA_PRO_MULTIPLIER,
    both: CREDIT_COSTS.BASE_BOTH_COST * CREDIT_COSTS.NANO_BANANA_PRO_MULTIPLIER,
    custom: CREDIT_COSTS.BASE_CUSTOM_COST * CREDIT_COSTS.NANO_BANANA_PRO_MULTIPLIER,
  },
} as const;

export type CreditCost = typeof CREDIT_COSTS;
export type ModelCreditCost = typeof MODEL_CREDIT_COSTS;
