/**
 * Centralized Stripe Payment Configuration
 *
 * This file contains all Stripe pricing and product configuration.
 * Auto-generated by stripe-setup.sh on Mon Dec  1 21:52:43 PST 2025
 */

import { clientEnv, serverEnv } from './env';

// Static Stripe Price IDs - Real Stripe Price IDs
export const STRIPE_PRICES = {
  // Subscriptions (Recurring payments) - ONLY subscription prices are allowed
  HOBBY_MONTHLY: 'price_1SZmVyALMLhQocpf0H7n5ls8',     // $19/month for 200 credits
  PRO_MONTHLY: 'price_1SZmVzALMLhQocpfPyRX2W8D', // $49/month for 1000 credits
  BUSINESS_MONTHLY: 'price_1SZmVzALMLhQocpfqPk9spg4', // $149/month for 5000 credits
} as const;

export type StripePriceKey = keyof typeof STRIPE_PRICES;

/**
 * Subscription plan metadata with credits, rollover, and feature details
 */
export interface ISubscriptionPlanMetadata {
  key: string;
  name: string;
  creditsPerMonth: number;
  maxRollover: number;
  features: readonly string[];
  recommended?: boolean;
}

/**
 * Subscription price map - single source of truth for plan validation and metadata
 * Maps Stripe price IDs to plan details
 */
export const SUBSCRIPTION_PRICE_MAP: Record<string, ISubscriptionPlanMetadata> = {
  [STRIPE_PRICES.HOBBY_MONTHLY]: {
    key: 'hobby',
    name: 'Hobby',
    creditsPerMonth: 200,
    maxRollover: 1200, // 6× monthly credits
    features: [
      '200 credits per month',
      'Rollover unused credits',
      'Email support',
      'All features included',
    ],
    recommended: false,
  },
  [STRIPE_PRICES.PRO_MONTHLY]: {
    key: 'pro',
    name: 'Professional',
    creditsPerMonth: 1000,
    maxRollover: 6000, // 6× monthly credits
    features: [
      '1000 credits per month',
      'Rollover unused credits',
      'Priority support',
      'All features included',
      'Early access to new features',
    ],
    recommended: true,
  },
  [STRIPE_PRICES.BUSINESS_MONTHLY]: {
    key: 'business',
    name: 'Business',
    creditsPerMonth: 5000,
    maxRollover: 30000, // 6× monthly credits
    features: [
      '5000 credits per month',
      'Rollover unused credits',
      '24/7 priority support',
      'All features included',
      'Dedicated account manager',
      'Custom integrations',
    ],
    recommended: false,
  },
} as const;

/**
 * Get plan metadata for a given Stripe price ID
 * Returns null if the price ID is not a valid subscription price
 */
export function getPlanForPriceId(priceId: string): ISubscriptionPlanMetadata | null {
  return SUBSCRIPTION_PRICE_MAP[priceId] ?? null;
}

/**
 * Get plan metadata by plan key (e.g., 'hobby', 'pro', 'business')
 * Returns null if the key is not found
 */
export function getPlanByKey(key: string): ISubscriptionPlanMetadata | null {
  const entry = Object.values(SUBSCRIPTION_PRICE_MAP).find((plan) => plan.key === key);
  return entry ?? null;
}

/**
 * Get human-readable plan display name from various input sources
 * This is the single source of truth for displaying plan names in UI components
 */
export function getPlanDisplayName(input: {
  priceId?: string | null;
  planKey?: string | null;
  subscriptionTier?: string | null;
}): string {
  const { priceId, planKey, subscriptionTier } = input;

  // Try subscription_tier first (most reliable, human-readable)
  if (subscriptionTier) {
    return subscriptionTier;
  }

  // Try priceId lookup
  if (priceId) {
    const plan = getPlanForPriceId(priceId);
    if (plan) {
      return plan.name;
    }
  }

  // Try planKey lookup
  if (planKey) {
    const plan = getPlanByKey(planKey);
    if (plan) {
      return plan.name;
    }
  }

  return 'Unknown Plan';
}

/**
 * Array of valid subscription price IDs for validation
 */
export const SUBSCRIPTION_PRICE_IDS = Object.keys(SUBSCRIPTION_PRICE_MAP);

/**
 * @deprecated Credit packs are no longer supported. Use subscriptions only.
 * This is kept for backwards compatibility but should not be used.
 */
export const CREDIT_PACKS = {} as const;

/**
 * Subscription plan configuration
 */
export const SUBSCRIPTION_PLANS = {
  HOBBY_MONTHLY: {
    name: 'Hobby',
    description: 'For personal projects',
    price: 19,
    interval: 'month' as const,
    creditsPerMonth: 200,
    features: [
      '200 credits per month',
      'Rollover unused credits',
      'Email support',
      'All features included',
    ],
  },
  PRO_MONTHLY: {
    name: 'Professional',
    description: 'For professionals',
    price: 49,
    interval: 'month' as const,
    creditsPerMonth: 1000,
    features: [
      '1000 credits per month',
      'Rollover unused credits',
      'Priority support',
      'All features included',
      'Early access to new features',
    ],
    recommended: true,
  },
  BUSINESS_MONTHLY: {
    name: 'Business',
    description: 'For teams and agencies',
    price: 149,
    interval: 'month' as const,
    creditsPerMonth: 5000,
    features: [
      '5000 credits per month',
      'Rollover unused credits',
      '24/7 priority support',
      'All features included',
      'Dedicated account manager',
      'Custom integrations',
    ],
  },
} as const;

/**
 * Check if Stripe prices are configured
 */
export function isStripePricesConfigured(): boolean {
  return true; // Always return true for static configuration
}

/**
 * Get the price ID for a given key, with validation
 */
export function getPriceId(key: StripePriceKey): string {
  const priceId = STRIPE_PRICES[key];
  if (!priceId || priceId.includes('000000000000000000000')) {
    console.warn(`Stripe Price ID for ${key} is not properly configured.`);
  }
  return priceId;
}

/**
 * Homepage pricing tiers - derived from subscription plans
 * Used by Pricing.tsx on homepage
 */
export const HOMEPAGE_TIERS = [
  {
    name: 'Free Tier',
    price: '$0',
    priceValue: 0,
    period: '/mo',
    description: 'For testing and personal use.',
    features: [
      '10 images per month',
      '2x & 4x Upscaling',
      'Basic Enhancement',
      'No watermark',
      '5MB file limit',
    ],
    cta: 'Start for Free',
    variant: 'outline' as const,
    priceId: null, // No Stripe price for free tier
    recommended: false,
  },
  {
    name: SUBSCRIPTION_PLANS.HOBBY_MONTHLY.name,
    price: `$${SUBSCRIPTION_PLANS.HOBBY_MONTHLY.price}`,
    priceValue: SUBSCRIPTION_PLANS.HOBBY_MONTHLY.price,
    period: '/mo',
    description: SUBSCRIPTION_PLANS.HOBBY_MONTHLY.description,
    features: SUBSCRIPTION_PLANS.HOBBY_MONTHLY.features,
    cta: 'Get Started',
    variant: 'secondary' as const,
    priceId: STRIPE_PRICES.HOBBY_MONTHLY,
    recommended: false,
  },
  {
    name: SUBSCRIPTION_PLANS.PRO_MONTHLY.name,
    price: `$${SUBSCRIPTION_PLANS.PRO_MONTHLY.price}`,
    priceValue: SUBSCRIPTION_PLANS.PRO_MONTHLY.price,
    period: '/mo',
    description: SUBSCRIPTION_PLANS.PRO_MONTHLY.description,
    features: SUBSCRIPTION_PLANS.PRO_MONTHLY.features,
    cta: 'Get Started',
    variant: 'primary' as const,
    priceId: STRIPE_PRICES.PRO_MONTHLY,
    recommended: true,
  },
] as const;

// =============================================================================
// Stripe Configuration Validation & Access
// =============================================================================

/**
 * Get the Stripe publishable key for client-side usage
 */
export function getStripePublishableKey(): string {
  return clientEnv.STRIPE_PUBLISHABLE_KEY;
}

/**
 * Get the Stripe secret key for server-side usage
 * Only accessible on the server
 */
export function getStripeSecretKey(): string {
  return serverEnv.STRIPE_SECRET_KEY || '';
}

/**
 * Get the Stripe webhook secret for server-side webhook verification
 */
export function getStripeWebhookSecret(): string {
  return serverEnv.STRIPE_WEBHOOK_SECRET || '';
}

/**
 * Complete Stripe configuration object
 * Use this to get all Stripe-related configuration in one place
 */
export function getStripeConfig(): {
  publishableKey: string;
  secretKey: string;
  webhookSecret: string;
  prices: typeof STRIPE_PRICES;
  subscriptionPlans: typeof SUBSCRIPTION_PLANS;
  subscriptionPriceMap: typeof SUBSCRIPTION_PRICE_MAP;
  homepageTiers: typeof HOMEPAGE_TIERS;
} {
  return {
    // Client-side configuration
    publishableKey: clientEnv.STRIPE_PUBLISHABLE_KEY,

    // Server-side configuration (only available on server)
    secretKey: serverEnv.STRIPE_SECRET_KEY || '',
    webhookSecret: serverEnv.STRIPE_WEBHOOK_SECRET || '',

    // Price IDs
    prices: STRIPE_PRICES,

    // Product configurations
    subscriptionPlans: SUBSCRIPTION_PLANS,
    subscriptionPriceMap: SUBSCRIPTION_PRICE_MAP,

    // Homepage pricing
    homepageTiers: HOMEPAGE_TIERS,
  };
}

/**
 * Validate that all required Stripe configuration is present
 * Returns an object with validation results
 */
export function validateStripeConfig(): {
  isValid: boolean;
  errors: string[];
  warnings: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Check client-side configuration
  if (!clientEnv.STRIPE_PUBLISHABLE_KEY) {
    errors.push('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY is not configured');
  } else if (clientEnv.STRIPE_PUBLISHABLE_KEY.includes('pk_test_xxx') || clientEnv.STRIPE_PUBLISHABLE_KEY.includes('pk_live_xxx')) {
    warnings.push('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY appears to be a placeholder key');
  }

  // Check server-side configuration
  if (!serverEnv.STRIPE_SECRET_KEY) {
    errors.push('STRIPE_SECRET_KEY is not configured');
  } else if (serverEnv.STRIPE_SECRET_KEY.includes('dummy') || serverEnv.STRIPE_SECRET_KEY.includes('placeholder')) {
    warnings.push('STRIPE_SECRET_KEY appears to be a dummy/placeholder key');
  }

  if (!serverEnv.STRIPE_WEBHOOK_SECRET) {
    warnings.push('STRIPE_WEBHOOK_SECRET is not configured - webhook signature verification will fail');
  }

  // Check price IDs
  const missingPrices = Object.entries(STRIPE_PRICES)
    .filter(([, priceId]) => !priceId || priceId.includes('000000000000000000000'))
    .map(([key]) => key);

  if (missingPrices.length > 0) {
    errors.push(`Missing or invalid Stripe Price IDs: ${missingPrices.join(', ')}`);
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
  };
}

/**
 * Check if Stripe is properly configured for payments
 * This is a convenience function that returns true if the essential configuration is present
 */
export function isStripeConfigured(): boolean {
  const validation = validateStripeConfig();
  return validation.isValid && serverEnv.STRIPE_SECRET_KEY.length > 0;
}
