/**
 * Centralized Stripe Payment Configuration
 *
 * This file contains all Stripe pricing and product configuration.
 * Auto-generated by stripe-setup.sh on Fri Dec  5 17:19:50 PST 2025
 */

import { clientEnv, serverEnv } from './env';

/**
 * Stripe subscription plan metadata interface
 */
export interface ISubscriptionPlanMetadata {
  name: string;
  creditsPerMonth: number;
  maxRollover: number;
}

// Static Stripe Price IDs - Real Stripe Price IDs
export const STRIPE_PRICES = {
  // Credit Packs (One-time payments)
  STARTER_CREDITS: 'price_1SbAA4ALMLhQocpfA57a2G0b', // $9.99 for 100 credits
  PRO_CREDITS: 'price_1SbAA4ALMLhQocpfkkV44bUG',        // $29.99 for 500 credits
  ENTERPRISE_CREDITS: 'price_1SbAA5ALMLhQocpfDCOGm405', // $99.99 for 2000 credits

  // Subscriptions (Recurring payments)
  HOBBY_MONTHLY: 'price_1SbAA5ALMLhQocpf7teu52vs',     // $19/month for 200 credits
  PRO_MONTHLY: 'price_1SbAA6ALMLhQocpfbImsPlcR', // $49/month for 1000 credits
  BUSINESS_MONTHLY: 'price_1SbAA6ALMLhQocpf9VAw4Dgu', // $149/month for 5000 credits
} as const;

export type StripePriceKey = keyof typeof STRIPE_PRICES;

/**
 * Credit pack configuration with associated credits
 */
export const CREDIT_PACKS = {
  STARTER_CREDITS: {
    name: 'Starter Pack',
    description: 'Perfect for trying out',
    price: 9.99,
    credits: 100,
    features: ['100 processing credits', 'Valid for 12 months', 'Email support', 'Basic features'],
  },
  PRO_CREDITS: {
    name: 'Pro Pack',
    description: 'Best value for regular users',
    price: 29.99,
    credits: 500,
    features: [
      '500 processing credits',
      'Valid for 12 months',
      'Priority email support',
      'All features included',
      '40% more credits',
    ],
    recommended: true,
  },
  ENTERPRISE_CREDITS: {
    name: 'Enterprise Pack',
    description: 'For power users',
    price: 99.99,
    credits: 2000,
    features: [
      '2000 processing credits',
      'Valid for 12 months',
      '24/7 priority support',
      'All features included',
      'Best value per credit',
    ],
  },
} as const;

/**
 * Subscription plan configuration
 */
export const SUBSCRIPTION_PLANS = {
  HOBBY_MONTHLY: {
    name: 'Hobby',
    description: 'For personal projects',
    price: 19,
    interval: 'month' as const,
    creditsPerMonth: 200,
    maxRollover: 400,
    key: 'HOBBY_MONTHLY',
    features: [
      '200 credits per month',
      'Rollover unused credits',
      'Email support',
      'All features included',
    ],
  },
  PRO_MONTHLY: {
    name: 'Professional',
    description: 'For professionals',
    price: 49,
    interval: 'month' as const,
    creditsPerMonth: 1000,
    maxRollover: 2000,
    key: 'PRO_MONTHLY',
    features: [
      '1000 credits per month',
      'Rollover unused credits',
      'Priority support',
      'All features included',
      'Early access to new features',
    ],
    recommended: true,
  },
  BUSINESS_MONTHLY: {
    name: 'Business',
    description: 'For teams and agencies',
    price: 149,
    interval: 'month' as const,
    creditsPerMonth: 5000,
    maxRollover: 10000,
    key: 'BUSINESS_MONTHLY',
    features: [
      '5000 credits per month',
      'Rollover unused credits',
      '24/7 priority support',
      'All features included',
      'Dedicated account manager',
      'Custom integrations',
    ],
  },
} as const;

/**
 * Check if Stripe prices are configured
 */
export function isStripePricesConfigured(): boolean {
  return true; // Always return true for static configuration
}

/**
 * Get the price ID for a given key, with validation
 */
export function getPriceId(key: StripePriceKey): string {
  const priceId = STRIPE_PRICES[key];
  if (!priceId || priceId.includes('000000000000000000000')) {
    console.warn(`Stripe Price ID for ${key} is not properly configured.`);
  }
  return priceId;
}

/**
 * Homepage pricing tiers - derived from subscription plans
 * Used by Pricing.tsx on homepage
 */
export const HOMEPAGE_TIERS = [
  {
    name: 'Free Tier',
    price: '$0',
    priceValue: 0,
    period: '/mo',
    description: 'For testing and personal use.',
    features: [
      '10 images per month',
      '2x & 4x Upscaling',
      'Basic Enhancement',
      'No watermark',
      '5MB file limit',
    ],
    cta: 'Start for Free',
    variant: 'outline' as const,
    priceId: null, // No Stripe price for free tier
    recommended: false,
  },
  {
    name: SUBSCRIPTION_PLANS.HOBBY_MONTHLY.name,
    price: `$${SUBSCRIPTION_PLANS.HOBBY_MONTHLY.price}`,
    priceValue: SUBSCRIPTION_PLANS.HOBBY_MONTHLY.price,
    period: '/mo',
    description: SUBSCRIPTION_PLANS.HOBBY_MONTHLY.description,
    features: SUBSCRIPTION_PLANS.HOBBY_MONTHLY.features,
    cta: 'Get Started',
    variant: 'secondary' as const,
    priceId: STRIPE_PRICES.HOBBY_MONTHLY,
    recommended: false,
  },
  {
    name: SUBSCRIPTION_PLANS.PRO_MONTHLY.name,
    price: `$${SUBSCRIPTION_PLANS.PRO_MONTHLY.price}`,
    priceValue: SUBSCRIPTION_PLANS.PRO_MONTHLY.price,
    period: '/mo',
    description: SUBSCRIPTION_PLANS.PRO_MONTHLY.description,
    features: SUBSCRIPTION_PLANS.PRO_MONTHLY.features,
    cta: 'Get Started',
    variant: 'primary' as const,
    priceId: STRIPE_PRICES.PRO_MONTHLY,
    recommended: true,
  },
] as const;

// =============================================================================
// Stripe Configuration Validation & Access
// =============================================================================

/**
 * Get the Stripe publishable key for client-side usage
 */
export function getStripePublishableKey(): string {
  return clientEnv.STRIPE_PUBLISHABLE_KEY;
}

/**
 * Get the Stripe secret key for server-side usage
 * Only accessible on the server
 */
export function getStripeSecretKey(): string {
  return serverEnv.STRIPE_SECRET_KEY || '';
}

/**
 * Get the Stripe webhook secret for server-side webhook verification
 */
export function getStripeWebhookSecret(): string {
  return serverEnv.STRIPE_WEBHOOK_SECRET || '';
}

/**
 * Complete Stripe configuration object
 * Use this to get all Stripe-related configuration in one place
 */
export function getStripeConfig(): {
  publishableKey: string;
  secretKey: string;
  webhookSecret: string;
  prices: typeof STRIPE_PRICES;
  creditPacks: typeof CREDIT_PACKS;
  subscriptionPlans: typeof SUBSCRIPTION_PLANS;
  homepageTiers: typeof HOMEPAGE_TIERS;
} {
  return {
    // Client-side configuration
    publishableKey: clientEnv.STRIPE_PUBLISHABLE_KEY,

    // Server-side configuration (only available on server)
    secretKey: serverEnv.STRIPE_SECRET_KEY || '',
    webhookSecret: serverEnv.STRIPE_WEBHOOK_SECRET || '',

    // Price IDs
    prices: STRIPE_PRICES,

    // Product configurations
    creditPacks: CREDIT_PACKS,
    subscriptionPlans: SUBSCRIPTION_PLANS,

    // Homepage pricing
    homepageTiers: HOMEPAGE_TIERS,
  };
}

/**
 * Validate that all required Stripe configuration is present
 * Returns an object with validation results
 */
export function validateStripeConfig(): {
  isValid: boolean;
  errors: string[];
  warnings: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Check client-side configuration
  if (!clientEnv.STRIPE_PUBLISHABLE_KEY) {
    errors.push('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY is not configured');
  } else if (clientEnv.STRIPE_PUBLISHABLE_KEY.includes('pk_test_xxx') || clientEnv.STRIPE_PUBLISHABLE_KEY.includes('pk_live_xxx')) {
    warnings.push('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY appears to be a placeholder key');
  }

  // Check server-side configuration
  if (!serverEnv.STRIPE_SECRET_KEY) {
    errors.push('STRIPE_SECRET_KEY is not configured');
  } else if (serverEnv.STRIPE_SECRET_KEY.includes('dummy') || serverEnv.STRIPE_SECRET_KEY.includes('placeholder')) {
    warnings.push('STRIPE_SECRET_KEY appears to be a dummy/placeholder key');
  }

  if (!serverEnv.STRIPE_WEBHOOK_SECRET) {
    warnings.push('STRIPE_WEBHOOK_SECRET is not configured - webhook signature verification will fail');
  }

  // Check price IDs
  const missingPrices = Object.entries(STRIPE_PRICES)
    .filter(([, priceId]) => !priceId || priceId.includes('000000000000000000000'))
    .map(([key]) => key);

  if (missingPrices.length > 0) {
    errors.push(`Missing or invalid Stripe Price IDs: ${missingPrices.join(', ')}`);
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
  };
}

/**
 * Get subscription plan details for a given price ID
 */
export function getPlanForPriceId(priceId: string): (typeof SUBSCRIPTION_PLANS)[keyof typeof SUBSCRIPTION_PLANS] | null {
  switch (priceId) {
    case STRIPE_PRICES.HOBBY_MONTHLY:
      return SUBSCRIPTION_PLANS.HOBBY_MONTHLY;
    case STRIPE_PRICES.PRO_MONTHLY:
      return SUBSCRIPTION_PLANS.PRO_MONTHLY;
    case STRIPE_PRICES.BUSINESS_MONTHLY:
      return SUBSCRIPTION_PLANS.BUSINESS_MONTHLY;
    default:
      return null;
  }
}

/**
 * Get display name for a subscription plan tier
 * Accepts either a string tier name or an object with priceId and subscriptionTier
 */
export function getPlanDisplayName(input: string | { priceId: string; subscriptionTier?: string | null }): string {
  if (typeof input === 'string') {
    // Handle string input (legacy support)
    switch (input.toLowerCase()) {
      case 'hobby':
      case 'HOBBY_MONTHLY':
        return SUBSCRIPTION_PLANS.HOBBY_MONTHLY.name;
      case 'pro':
      case 'professional':
      case 'PRO_MONTHLY':
        return SUBSCRIPTION_PLANS.PRO_MONTHLY.name;
      case 'business':
      case 'BUSINESS_MONTHLY':
        return SUBSCRIPTION_PLANS.BUSINESS_MONTHLY.name;
      default:
        return input;
    }
  }

  // Handle object input with priceId and subscriptionTier
  const { priceId, subscriptionTier } = input;

  // First try to get plan by priceId
  const plan = getPlanForPriceId(priceId);
  if (plan) {
    return plan.name;
  }

  // Fallback to subscriptionTier
  if (subscriptionTier) {
    return getPlanDisplayName(subscriptionTier);
  }

  // Final fallback
  return 'Unknown Plan';
}

/**
 * Check if Stripe is properly configured for payments
 * This is a convenience function that returns true if the essential configuration is present
 */
export function isStripeConfigured(): boolean {
  const validation = validateStripeConfig();
  return validation.isValid && serverEnv.STRIPE_SECRET_KEY.length > 0;
}
