#!/bin/bash

# ============================================================================
# Supabase Complete Setup Script
# ============================================================================
# This script sets up all Supabase infrastructure for PixelPerfect
#
# Usage:
#   ./scripts/setup-supabase.sh [options]
#
# Options:
#   --dry-run     Show what would be executed without running
#   --skip-verify Skip verification step
#   --manual      Generate combined SQL for manual execution
#   --help        Show this help message
#
# Prerequisites:
#   - Supabase CLI installed (optional, can use manual mode)
#   - Environment variables set in .env and .env.prod
# ============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
MIGRATIONS_DIR="$PROJECT_ROOT/supabase/migrations"
OUTPUT_DIR="$PROJECT_ROOT/supabase"

# Flags
DRY_RUN=false
SKIP_VERIFY=false
MANUAL_MODE=false

# ============================================================================
# Helper Functions
# ============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${CYAN}[STEP]${NC} $1"
}

show_help() {
    echo "Supabase Complete Setup Script"
    echo ""
    echo "Usage: ./scripts/setup-supabase.sh [options]"
    echo ""
    echo "Options:"
    echo "  --dry-run     Show what would be executed without running"
    echo "  --skip-verify Skip verification step"
    echo "  --manual      Generate combined SQL file for manual execution"
    echo "  --help, -h    Show this help message"
    echo ""
    echo "Examples:"
    echo "  ./scripts/setup-supabase.sh              # Run with Supabase CLI"
    echo "  ./scripts/setup-supabase.sh --manual     # Generate SQL for dashboard"
    echo "  ./scripts/setup-supabase.sh --dry-run    # Preview actions"
    exit 0
}

# ============================================================================
# Parse Arguments
# ============================================================================

while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --skip-verify)
            SKIP_VERIFY=true
            shift
            ;;
        --manual)
            MANUAL_MODE=true
            shift
            ;;
        --help|-h)
            show_help
            ;;
        *)
            log_error "Unknown option: $1"
            show_help
            ;;
    esac
done

echo ""
echo "============================================"
echo "  Supabase Setup for PixelPerfect"
echo "============================================"
echo ""

# ============================================================================
# Define Migrations in Order
# ============================================================================

MIGRATIONS=(
    "20250120_create_profiles_table.sql"
    "20250120_create_subscriptions_table.sql"
    "20250121_create_credit_transactions_table.sql"
    "20250121_create_processing_jobs_table.sql"
    "20250120_create_rpc_functions.sql"
    "20250121_enhanced_credit_functions.sql"
    "20250121_fix_initial_credits.sql"
)

# ============================================================================
# Validate Migration Files
# ============================================================================

log_step "Validating migration files..."

MISSING_FILES=()
for migration in "${MIGRATIONS[@]}"; do
    migration_path="$MIGRATIONS_DIR/$migration"
    if [[ ! -f "$migration_path" ]]; then
        MISSING_FILES+=("$migration")
    fi
done

if [[ ${#MISSING_FILES[@]} -gt 0 ]]; then
    log_error "Missing migration files:"
    for f in "${MISSING_FILES[@]}"; do
        echo "  - $f"
    done
    echo ""
    echo "Please ensure all migrations exist in: $MIGRATIONS_DIR"
    exit 1
fi

log_success "All ${#MIGRATIONS[@]} migration files found"

# ============================================================================
# Manual Mode - Generate Combined SQL
# ============================================================================

if [[ "$MANUAL_MODE" == "true" ]]; then
    OUTPUT_FILE="$OUTPUT_DIR/combined_setup.sql"

    log_step "Generating combined SQL file..."

    # Create header
    cat > "$OUTPUT_FILE" << 'EOF'
-- ============================================================================
-- PixelPerfect Supabase Complete Setup
-- ============================================================================
-- Generated by setup-supabase.sh
--
-- Instructions:
-- 1. Open Supabase Dashboard > SQL Editor
-- 2. Copy and paste this entire file
-- 3. Click "Run" to execute
--
-- This script is idempotent - safe to run multiple times
-- ============================================================================

EOF

    # Append each migration
    for migration in "${MIGRATIONS[@]}"; do
        migration_path="$MIGRATIONS_DIR/$migration"
        echo "" >> "$OUTPUT_FILE"
        echo "-- ========================================" >> "$OUTPUT_FILE"
        echo "-- Migration: $migration" >> "$OUTPUT_FILE"
        echo "-- ========================================" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        cat "$migration_path" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    done

    log_success "Combined SQL generated: $OUTPUT_FILE"
    echo ""
    echo "Next steps:"
    echo "  1. Open: https://supabase.com/dashboard/project/YOUR_PROJECT/sql"
    echo "  2. Paste contents of: $OUTPUT_FILE"
    echo "  3. Click 'Run'"
    echo ""
    exit 0
fi

# ============================================================================
# Environment Validation
# ============================================================================

log_step "Checking environment variables..."

# Load environment files
if [[ -f "$PROJECT_ROOT/.env" ]]; then
    set -a
    # shellcheck source=/dev/null
    source "$PROJECT_ROOT/.env"
    set +a
fi

if [[ -f "$PROJECT_ROOT/.env.prod" ]]; then
    set -a
    # shellcheck source=/dev/null
    source "$PROJECT_ROOT/.env.prod"
    set +a
fi

# Required variables
REQUIRED_VARS=(
    "NEXT_PUBLIC_SUPABASE_URL"
    "SUPABASE_SERVICE_ROLE_KEY"
)

MISSING_VARS=()
for var in "${REQUIRED_VARS[@]}"; do
    if [[ -z "${!var:-}" ]]; then
        MISSING_VARS+=("$var")
    fi
done

if [[ ${#MISSING_VARS[@]} -gt 0 ]]; then
    log_error "Missing required environment variables:"
    for var in "${MISSING_VARS[@]}"; do
        echo "  - $var"
    done
    echo ""
    echo "Ensure these are set in .env and/or .env.prod"
    echo ""
    echo "Alternatively, use --manual mode to generate SQL for dashboard execution."
    exit 1
fi

log_success "Environment variables validated"

# ============================================================================
# Supabase Connection Test
# ============================================================================

log_step "Testing Supabase connection..."

# Extract project ref from URL
SUPABASE_PROJECT_REF=$(echo "$NEXT_PUBLIC_SUPABASE_URL" | sed -E 's|https://([^.]+)\.supabase\.co.*|\1|')

if [[ -z "$SUPABASE_PROJECT_REF" ]]; then
    log_error "Could not extract project ref from SUPABASE_URL"
    exit 1
fi

if [[ "$DRY_RUN" == "false" ]]; then
    # Test connection with a simple query
    TEST_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
        "${NEXT_PUBLIC_SUPABASE_URL}/rest/v1/" \
        -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
        -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" 2>/dev/null || echo "000")

    if [[ "$TEST_RESPONSE" != "200" ]]; then
        log_error "Failed to connect to Supabase (HTTP $TEST_RESPONSE)"
        echo ""
        echo "Please check:"
        echo "  - NEXT_PUBLIC_SUPABASE_URL is correct"
        echo "  - SUPABASE_SERVICE_ROLE_KEY is valid"
        echo "  - Network connectivity"
        exit 1
    fi
fi

log_success "Connected to Supabase project: $SUPABASE_PROJECT_REF"

# ============================================================================
# Check for Supabase CLI
# ============================================================================

HAS_CLI=false
if command -v supabase &> /dev/null; then
    HAS_CLI=true
    CLI_VERSION=$(supabase --version 2>/dev/null || echo "unknown")
    log_success "Supabase CLI found: $CLI_VERSION"
else
    log_warning "Supabase CLI not installed"
    echo ""
    echo "To install:"
    echo "  brew install supabase/tap/supabase   # macOS"
    echo "  npm install -g supabase              # npm"
    echo "  npx supabase                         # npx (no install)"
    echo ""

    if [[ "$DRY_RUN" == "false" ]]; then
        read -p "Continue without CLI? Will show SQL to run manually. [y/N] " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo ""
            echo "Tip: Use --manual flag to generate combined SQL file"
            exit 1
        fi
    fi
fi

# ============================================================================
# Apply Migrations
# ============================================================================

log_step "Applying migrations..."

APPLIED_COUNT=0
FAILED_MIGRATIONS=()

for migration in "${MIGRATIONS[@]}"; do
    migration_path="$MIGRATIONS_DIR/$migration"

    echo -n "  Applying: $migration ... "

    if [[ "$DRY_RUN" == "true" ]]; then
        echo -e "${YELLOW}[DRY-RUN]${NC}"
        ((APPLIED_COUNT++))
        continue
    fi

    if [[ "$HAS_CLI" == "true" ]]; then
        # Use Supabase CLI
        cd "$PROJECT_ROOT"

        # Link project if not already linked
        if [[ ! -f "$PROJECT_ROOT/supabase/.temp/project-ref" ]]; then
            supabase link --project-ref "$SUPABASE_PROJECT_REF" 2>/dev/null || true
        fi

        # Try to push the migration
        if supabase db push 2>/dev/null; then
            echo -e "${GREEN}OK${NC}"
            ((APPLIED_COUNT++))
        else
            echo -e "${YELLOW}SKIPPED (may already exist)${NC}"
            ((APPLIED_COUNT++))
        fi
    else
        # No CLI - just report what needs to be done
        echo -e "${YELLOW}MANUAL${NC}"
        FAILED_MIGRATIONS+=("$migration")
    fi
done

echo ""

if [[ ${#FAILED_MIGRATIONS[@]} -gt 0 ]]; then
    log_warning "The following migrations need manual application:"
    echo ""
    for m in "${FAILED_MIGRATIONS[@]}"; do
        echo "  $MIGRATIONS_DIR/$m"
    done
    echo ""
    echo "Run these in Supabase Dashboard SQL Editor:"
    echo "  https://supabase.com/dashboard/project/$SUPABASE_PROJECT_REF/sql"
    echo ""
    echo "Or use: ./scripts/setup-supabase.sh --manual"
else
    log_success "Applied $APPLIED_COUNT migrations"
fi

# ============================================================================
# Verification
# ============================================================================

if [[ "$SKIP_VERIFY" == "false" && "$DRY_RUN" == "false" ]]; then
    log_step "Verification checklist..."
    echo ""
    echo "Please verify in Supabase Dashboard:"
    echo ""
    echo "Tables (Database > Tables):"
    echo "  [ ] profiles"
    echo "  [ ] subscriptions"
    echo "  [ ] products"
    echo "  [ ] prices"
    echo "  [ ] credit_transactions"
    echo "  [ ] processing_jobs"
    echo ""
    echo "RPC Functions (Database > Functions):"
    echo "  [ ] increment_credits"
    echo "  [ ] decrement_credits"
    echo "  [ ] increment_credits_with_log"
    echo "  [ ] decrement_credits_with_log"
    echo "  [ ] has_sufficient_credits"
    echo "  [ ] get_active_subscription"
    echo "  [ ] refund_credits"
    echo ""
    echo "Triggers (Database > Triggers):"
    echo "  [ ] on_auth_user_created (on auth.users)"
    echo "  [ ] on_profiles_updated (on profiles)"
    echo "  [ ] on_processing_jobs_updated (on processing_jobs)"
    echo ""
    echo "RLS (each table should show 'RLS Enabled'):"
    echo "  [ ] All tables have RLS enabled"
    echo ""
fi

# ============================================================================
# Summary
# ============================================================================

echo ""
echo "============================================"
if [[ "$DRY_RUN" == "true" ]]; then
    log_success "Dry run complete!"
else
    log_success "Setup complete!"
fi
echo "============================================"
echo ""

echo "Next steps:"
echo "  1. Enable Realtime on 'profiles' table:"
echo "     Dashboard > Database > Replication > Enable for 'profiles'"
echo ""
echo "  2. Test by creating a new user:"
echo "     - Sign up should create profile with 10 credits"
echo "     - Transaction should be logged in credit_transactions"
echo ""
echo "  3. Verify webhook is configured:"
echo "     Dashboard > Settings > Webhooks (for Stripe integration)"
echo ""

if [[ "$DRY_RUN" == "false" ]]; then
    echo "Dashboard link:"
    echo "  https://supabase.com/dashboard/project/$SUPABASE_PROJECT_REF"
fi
echo ""
